<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLljMmcE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLljMmcE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLljMmcE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLljMmcE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLljMmcE\App_KernelDevDebugContainer([
    'container.build_hash' => 'LljMmcE',
    'container.build_id' => 'e5198e92',
    'container.build_time' => 1609184650,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLljMmcE');
