<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcbSkBa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcbSkBa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcbSkBa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcbSkBa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcbSkBa\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcbSkBa',
    'container.build_id' => 'a48f424c',
    'container.build_time' => 1609181583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcbSkBa');
