<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQrQzF9I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQrQzF9I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQrQzF9I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQrQzF9I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQrQzF9I\App_KernelDevDebugContainer([
    'container.build_hash' => 'QrQzF9I',
    'container.build_id' => 'ad2d708b',
    'container.build_time' => 1609078106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQrQzF9I');
