<?php

namespace ContainerSugUWXu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0UkopjSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0UkopjS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0UkopjS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pagejeu' => ['privates', '.errored..service_locator.0UkopjS.App\\Entity\\Pagejeu', NULL, 'Cannot autowire service ".service_locator.0UkopjS": it references class "App\\Entity\\Pagejeu" but no such service exists.'],
        ], [
            'pagejeu' => 'App\\Entity\\Pagejeu',
        ]);
    }
}
