<?php

namespace ContainerSugUWXu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagejeuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0UkopjS.App\Entity\Pagejeu' shared service.
     *
     * @return \App\Entity\Pagejeu
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0UkopjS": it references class "App\\Entity\\Pagejeu" but no such service exists.');
    }
}
